import Header from '@/components/Header'
import PromptInput from '@/components/PromptInput'
import '../styles/global.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='bg-primary'>
        {/* Header */}
        <Header/>

        {/* Prompt Input */}
        <PromptInput/>
        {children}
        </body>
    </html>
  )
}
